# Use uma imagem base do Python
FROM python:3.12-slim-bookworm

# Defina variáveis de ambiente para produção
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1 \
    FLASK_ENV=production \
    FLASK_APP=app.py

# Crie e defina o diretório de trabalho
WORKDIR /app

# Instale dependências do sistema, incluindo Graphviz
RUN apt-get update && apt-get install -y --no-install-recommends \
    graphviz \
    && rm -rf /var/lib/apt/lists/*

# Copie o arquivo de requisitos e instale dependências do Python
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copie o código da aplicação
COPY . .

# Crie o diretório de upload
RUN mkdir -p static/uploads && chmod 777 static/uploads

# Exponha a porta
EXPOSE 5000

# Execute a aplicação
CMD ["python", "app.py"]